/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package unired.api.nominas;

/**
 *
 * @author jsilvab
 */
public class Querys {

    //Nominas ---------------------------------------------------------------------------------------------------
    public static final String RESUMEN_NOMINAS = ""
	    + "SELECT \n"
	    + " COUNT(1) total,"
	    + "	SUM(CASE WHEN b.id_estado = 1 then 1 else 0 end) exitoso,\n"
	    + "	SUM(CASE WHEN b.id_estado = 2 then 1 else 0 end) error,\n"
	    + "	SUM(CASE WHEN b.id_estado = 3 then 1 else 0 end) norecibida,\n"
	    + "	SUM(CASE WHEN b.id_estado = 4 then 1 else 0 end) sinprocesar,\n"
	    + "	SUM(CASE WHEN b.id_estado = 6 then 1 else 0 end) parcialmente,\n"
	    + "	SUM(CASE WHEN b.id_estado = 7 then 1 else 0 end) nocumple,\n"
	    + "	SUM(CASE WHEN b.id_estado is null then 1 else 0 end) pendiente,\n"
	    + "	SUM(CASE WHEN b.id_estado is null then 0 else 1 end) ejecutados\n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1";

    public static final String QUERY_PROGRAMADAS = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1";

    public static final String QUERY_EJECUTADOS = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado is not null";

    public static final String QUERY_EXITOSAS = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 1";

    public static final String QUERY_ERRORES = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 2";

    public static final String QUERY_PENDIENTES = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado is null";

    public static final String QUERY_NO_RECIBIDAS = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 3";

    public static final String QUERY_SIN_PROCESAR = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 4";

    public static final String QUERY_PARCIALMENTE = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 6";

    public static final String QUERY_NO_CUMPLE = ""
	    + "SELECT \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	a.cod_empresa codEmpresa,\n"
	    + "	a.glosa_empresa nomEmpresa,\n"
	    + "	a.per_inicio horaIni,\n"
	    + "	a.per_final horaFin,\n"
	    + "	b.fecha_proceso fechaProceso,\n"
	    + "	b.fecha_termino fechaTermino,\n"
	    + "	datediff(MINUTE, b.fecha_proceso, b.fecha_termino) minutos,\n"
	    + "	b.id_estado idEstado,\n"
	    + "	c.glosa_estado estado \n"
	    + "FROM 	\n"
	    + "	tbl_EmpUnimarc a LEFT JOIN tbl_LogUnimarc b \n"
	    + "	ON a.id_empresa  = b.id_empresa \n"
	    + "		and convert(date, b.fecha_proceso) = convert(date, getdate()) LEFT JOIN tbl_EstaUnimarc c\n"
	    + "	ON b.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.estado = 1\n"
	    + "	and b.id_estado = 7";

    public static final String HISTORIA = ""
	    + "select \n"
	    + "	a.id_empresa idEmpresa,\n"
	    + "	b.cod_empresa codEmpresa,\n"
	    + "	b.glosa_empresa nomEmpresa,\n"
	    + "	b.per_inicio horaIni,\n"
	    + "	b.per_final horaFin,\n"
	    + "	a.fecha_proceso fechaProceso,\n"
	    + "	a.fecha_termino fechaTermino,\n"
	    + "	DATEDIFF(MINUTE, a.fecha_proceso, a.fecha_termino) minutos,\n"
	    + "	c.id_estado idEstado,\n"
	    + "	c.glosa_estado estado\n"
	    + "FROM \n"
	    + "	tbl_LogUnimarc a INNER JOIN tbl_EmpUnimarc b \n"
	    + "	on a.id_empresa = b.cod_empresa INNER JOIN tbl_EstaUnimarc c\n"
	    + "	on a.id_estado = c.id_estado \n"
	    + "WHERE \n"
	    + "	a.fecha_proceso BETWEEN '${fechaIni}' AND '${fechaFin}'\n"
	    + "	";
}
