package unired.api.rendiciones;

import java.time.LocalDate;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

@Mapper
public interface ProcesoMapper {

    final String QUERY_CUENTA_PROCESOS = "SELECT \n"
	    + "	COUNT(DISTINCT d.IdDefinicionArchivos) total,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 56 THEN 1 ELSE 0 END) enEspera,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 25 THEN 1 ELSE 0 END) pendiente,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 26 THEN 1 ELSE 0 END) enEjecucion,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 27 THEN 1 ELSE 0 END) generado,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 28 THEN 1 ELSE 0 END) transmitido,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 29 THEN 1 ELSE 0 END) fallaEnProceso,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 40 THEN 1 ELSE 0 END) enviadoAMail,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso = 4046 THEN 1 ELSE 0 END) rendicionVacia,\n"
	    + "	SUM(CASE WHEN s.EstadoProceso IN(27, 40, 4046) THEN 1 END) exitoso\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) \n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)";

    final String QUERY_PROCESO_UNICO = "SELECT \n"
	    + "	s.IdProceso,\n"
	    + "	s.IdEmpresa,\n"
	    + "	e.NombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	CASE \n"
	    + "		WHEN s.EstadoProceso = 56 THEN 'En Espera'\n"
	    + "		WHEN s.EstadoProceso = 25 THEN 'Pendiente'\n"
	    + "		WHEN s.EstadoProceso = 26 THEN 'En Ejecución'\n"
	    + "		WHEN s.EstadoProceso = 27 THEN 'Generado'\n"
	    + "		WHEN s.EstadoProceso = 28 THEN 'Transmitido'\n"
	    + "		WHEN s.EstadoProceso = 29 THEN 'Falla en el Proceso'\n"
	    + "		WHEN s.EstadoProceso = 40 THEN 'Enviado a Mail'\n"
	    + "		WHEN s.EstadoProceso = 4046 THEN 'Rendición Vacía' \n"
	    + "	END AS estado,\n"
	    + "	s.FechaProceso,\n"
	    + "	s.FechaCreacion,\n"
	    + "	s.InicioProceso,\n"
	    + "	s.FinProceso\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + "	AND s.IdProceso = #{idProceso}\n"
	    + "ORDER BY\n"
	    + "	s.FechaCreacion DESC";

    final String QUERY_SUB_PROCESOS = "SELECT\n"
	    + "	IdBitacora,\n"
	    + "    Descripcion,\n"
	    + "    EventosProceso,\n"
	    + "    FechaCreacion,\n"
	    + "    Procesos_IdProceso\n"
	    + "FROM\n"
	    + "	BitacoraProcesos\n"
	    + "WHERE\n"
	    + "	Procesos_IdProceso = #{idProceso}\n"
	    + "ORDER BY\n"
	    + "	IdBitacora ASC";

    @Select("SELECT * FROM Procesos a inner join Empresas b on a.IdEmpresa = b.IdEmpresa WHERE IdProceso = #{idProceso}")
    Proceso getProceso(Integer idProceso);

    @Select("SELECT \n"
	    + "	COUNT(DISTINCT d.IdDefinicionArchivos) CANT\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado)\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)")
    Integer getProcesosActivos();

    @Select(QUERY_CUENTA_PROCESOS)
    Procesos getCuentaProcesos();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	CASE \n"
	    + "		WHEN s.EstadoProceso = 56 THEN 'En Espera'\n"
	    + "		WHEN s.EstadoProceso = 25 THEN 'Pendiente'\n"
	    + "		WHEN s.EstadoProceso = 26 THEN 'En Ejecución'\n"
	    + "		WHEN s.EstadoProceso = 27 THEN 'Generado'\n"
	    + "		WHEN s.EstadoProceso = 28 THEN 'Transmitido'\n"
	    + "		WHEN s.EstadoProceso = 29 THEN 'Falla en el Proceso'\n"
	    + "		WHEN s.EstadoProceso = 40 THEN 'Enviado a Mail'\n"
	    + "		WHEN s.EstadoProceso = 4046 THEN 'Rendición Vacía' \n"
	    + "	END AS estado,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + "ORDER BY\n"
	    + "	s.IdProceso ASC")
    List<Proceso> getProcesosDia();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso = #{codEstado}"
	    + "ORDER BY\n"
	    + "	s.IdProceso ASC")
    List<Proceso> getProcesosDiaCodEstado(Integer codEstado);

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso in(27,28,29,40,4046) "
	    + " ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosDiaEjecutados();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso in(27,40,4046) "
	    + " ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosDiaExitosos();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " and s.EstadoProceso = 29")
    List<Proceso> getProcesosDiaErrores();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso IN (56, 25) "
	    + " ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosDiaPendientes();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso = 40 "
	    + "ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosDiaEnviadoMail();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso = 4046 "
	    + " ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosRendicionVacia();

    @Select("SELECT \n"
	    + "	s.IdProceso idProceso,\n"
	    + "	s.IdEmpresa idEmpresa,\n"
	    + "	e.NombreEps nombreEps,\n"
	    + "	s.EstadoProceso estadoProceso,\n"
	    + "	s.FechaProceso fechaProceso,\n"
	    + "	s.FechaCreacion fechaCreacion,\n"
	    + "	s.InicioProceso inicioProceso,\n"
	    + "	s.FinProceso finProceso,\n"
	    + "	p.TipoCorte,\n"
	    + "	d.TipoRendicion,\n"
	    + "	d.IdDefinicionArchivos\n"
	    + "FROM \n"
	    + "	TareasProgramadas t inner join PlanRendiciones p\n"
	    + "	on t.PlanRendiciones_IdEmpresa = p.IdEmpresa inner join  DefinicionArchivos d\n"
	    + "	on d.IdEmpresa = p.IdEmpresa inner join Procesos s\n"
	    + "	on d.IdDefinicionArchivos = s.DefinicionArchivos_IdDefinicionArchivos left join Feriados f\n"
	    + "	on CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, f.FechaFeriado) inner join Empresas e\n"
	    + "	on s.IdEmpresa = e.IdEmpresa\n"
	    + "WHERE \n"
	    + "	t.Vigente = 'S'\n"
	    + "	and d.Vigente = 'S'		\n"
	    + "	AND\n"
	    + "	(\n"
	    + "		((CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, DATEADD(DAY, -1, GETDATE()))) and (d.TipoRendicion != 97 and d.TipoRendicion != 99))\n"
	    + "	 		OR\n"
	    + "		(CONVERT(DATE, s.FechaCreacion) = CONVERT(DATE, GETDATE()) and s.EstadoProceso != 56)\n"
	    + "			OR\n"
	    + "		(\n"
	    + "			p.TipoCorte = '14' and d.TipoRendicion = 97\n"
	    + "				and\n"
	    + "			(\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 7\n"
	    + "      				or\n"
	    + "				(DATEPART(WEEKDAY, CONVERT(DATE, DATEADD(DAY, 0, GETDATE())))) = 1\n"
	    + "	  				or\n"
	    + "				(CONVERT(DATE, GETDATE()) = (CONVERT(DATE, f.FechaFeriado)))\n"
	    + "	  		)\n"
	    + "		)\n"
	    + "	)\n"
	    + " AND s.EstadoProceso = 26 "
	    + " ORDER BY s.IdProceso ASC")
    List<Proceso> getProcesosRendicionEjecucion();

    @Select(QUERY_SUB_PROCESOS)
    List<SubProceso> getSubProcesosIdProceso(Integer idProceso);

}
